name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: checkboxes
    id: security
    attributes:
      label: Security Check
      description: Please confirm this is NOT a security vulnerability
      options:
        - label: This is NOT a security vulnerability (security issues must be reported via SECURITY.md)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Create a key with...
        2. Call encrypt with...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproduction Code
      description: If applicable, provide minimal code that demonstrates the issue
      render: rust
      placeholder: |
        use latticearc::prelude::*;

        fn main() {
            // Your reproduction code here
        }

  - type: input
    id: version
    attributes:
      label: LatticeArc Version
      description: What version are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.93.0 (2024-xx-xx)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (x86_64)
        - Linux (aarch64)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (x86_64)
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, logs, or information that might be helpful
      placeholder: Stack traces, feature flags used, etc.
