name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: checkboxes
    id: search
    attributes:
      label: Existing Issues
      description: Please confirm you've searched existing issues
      options:
        - label: I have searched existing issues and this feature has not been requested
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Cryptographic Primitives (KEM, signatures, etc.)
        - Hybrid Encryption
        - TLS Integration
        - API Ergonomics
        - Performance
        - Documentation
        - Testing/Validation
        - Build/CI
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: |
        I'm trying to...
        Currently I have to...
        This is problematic because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution
      placeholder: |
        I would like to be able to...
        The API could look like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        I've tried using X but...
        Alternative approaches include...

  - type: textarea
    id: api
    attributes:
      label: Proposed API (if applicable)
      description: If this is an API change, show the proposed interface
      render: rust
      placeholder: |
        // Example of how the API might look
        pub fn new_feature(input: &[u8]) -> Result<Output>;

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this?
      options:
        - label: I would be willing to submit a PR to implement this feature

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, references, or information
      placeholder: Related RFCs, similar implementations in other libraries, etc.
